/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AESInterop */

#ifndef _Included_AESInterop
#define _Included_AESInterop
#ifdef __cplusplus
extern "C" {
#endif
#undef AESInterop_AES_KEY_SIZE
#define AESInterop_AES_KEY_SIZE 16L
#undef AESInterop_AES_IV_SIZE
#define AESInterop_AES_IV_SIZE 16L
#undef AESInterop_MAX_BUFFER_SIZE
#define AESInterop_MAX_BUFFER_SIZE 1024L
/*
 * Class:     AESInterop
 * Method:    GenerateAESKey
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_AESInterop_GenerateAESKey
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     AESInterop
 * Method:    SaveKeyToFile
 * Signature: (Ljava/lang/String;[B[B)V
 */
JNIEXPORT void JNICALL Java_AESInterop_SaveKeyToFile
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray);

/*
 * Class:     AESInterop
 * Method:    LoadKeyFromFile
 * Signature: (Ljava/lang/String;[B[B)V
 */
JNIEXPORT void JNICALL Java_AESInterop_LoadKeyFromFile
  (JNIEnv *, jobject, jstring, jbyteArray, jbyteArray);

/*
 * Class:     AESInterop
 * Method:    AESEncrypt
 * Signature: ([B[BLjava/lang/String;[BI)V
 */
JNIEXPORT void JNICALL Java_AESInterop_AESEncrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jstring, jbyteArray, jint);

/*
 * Class:     AESInterop
 * Method:    AESDecrypt
 * Signature: ([B[BLjava/lang/String;[BI)V
 */
JNIEXPORT void JNICALL Java_AESInterop_AESDecrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jstring, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
